"""AI-assisted evidence classification; produces no review record or approval."""
import collections
import datetime as dt
import hashlib
import importlib.util
import json
from pathlib import Path
import sys

# Reuse the unchanged prior parser without writing generated bytecode into its evidence folder.
sys.dont_write_bytecode = True

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
OLD = HERE.parent / '2026-09-16'
spec = importlib.util.spec_from_file_location('prior_inventory', OLD / 'inventory.py')
prior = importlib.util.module_from_spec(spec)
spec.loader.exec_module(prior)
prior.HERE = HERE
PRIORITY = {'bangalore', 'chennai', 'delhi', 'guwahati', 'hyderabad', 'london', 'mayapur'}

def read(p): return json.loads(p.read_text(encoding='utf-8-sig'))
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p, value):
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(value, indent=2, ensure_ascii=False), encoding='utf-8')
def evidence(p, outcome): return dict(link=p.relative_to(ROOT).as_posix(), sha256=sha(p), outcome=outcome)

def main():
    measurements = sorted((HERE / 'measurements').glob('*.json'))
    assert len(measurements) == 45
    rows = [prior.compare(read(p)) for p in measurements]
    old_rows = {(r['city'], r['year']): r for r in read(OLD/'coverage-inventory.json')['sites']}
    reproduction = []
    for row in rows:
        old = old_rows[row['city'], row['year']]
        reproduction.append(dict(city=row['city'], year=row['year'], resultUnchanged=row['resultSha256']==old['resultSha256'],
                                 comparisonsUnchanged=row['fields']==old['fields'] and row['details']==old['details']))
    assert all(r['resultUnchanged'] and r['comparisonsUnchanged'] for r in reproduction)
    write(HERE/'reproduction-checks.json', reproduction)
    write(HERE/'coverage-inventory.json', dict(classification='AI_ASSISTED_EVIDENCE_REVIEW', sites=rows,
         noQualifiedReviewCreated=True, noOwnerApprovalCreated=True, runtimeDisputesUnchanged=True))
    report = []
    for row in rows:
        if row['year'] != 2026: continue
        city = row['city']
        measurement = read(HERE/f'measurements/{city}-2026.json')
        bounds = [d for d in row['details'] if d['field'] in ('paranaStart','paranaEnd')]
        usable = [d for d in bounds if d['status']=='WITHIN_EXISTING_BAND' and d['basisStatus']=='MATCH']
        exact = sum(dt.datetime.fromisoformat(d['calculated']['local']).strftime('%H:%M')==d['reference'] for d in usable)
        obs_issues = [d for d in prior.REGISTRY['disputes'] if d['id'] in row['runtimeIssueIds'] and 'OBSERVANCES' in d['fields']]
        groups = []
        for group in ('OBSERVANCES','EVENTS','DAILY_ASTRONOMY'):
            fields = row['fields'][:5] if group=='OBSERVANCES' else row['fields'][9:11] if group=='EVENTS' else row['fields'][5:9] + row['fields'][11:]
            groups.append(dict(fieldGroup=group, proposed=group=='OBSERVANCES' and city in PRIORITY,
                evidenceSupported=[f for f in fields if f['status'].startswith('SUFFICIENT')],
                conflicting=[f for f in fields if f.get('disagreements',0)],
                missingEvidence=[f for f in fields if f.get('unavailable',0) or f['status'].startswith(('PARTIAL','UNAVAILABLE'))],
                missingContextualEvidence=['Exact export binary/settings/elevation not authenticated; assumption requires review.',
                    'No positive calculated Jaya/Jayanti/Papanasini validation in this sample.'] if group=='OBSERVANCES' else [],
                technicalStatus='TECHNICALLY_PREPARED_AWAITING_EXISTING_APPROVAL_REQUIREMENTS' if group=='OBSERVANCES' and city in PRIORITY else 'HELD_NOT_PROPOSED',
                applicableRuntimeCases=[d for d in prior.REGISTRY['disputes'] if d['id'] in row['runtimeIssueIds'] and group in d['fields']],
                applicableReviewQuestions=[q['id'] for q in prior.REGISTRY['reviewQuestions'] if 'iskcon' in q['traditions'] and group in q['fields']]))
        # Review complete December / January context, including every disagreement, not just availability.
        context = []
        for year, month in [(2025,'12'),(2027,'01')]:
            other = next(r for r in rows if r['city']==city and r['year']==year)
            relevant = [d for d in other['details'] if d.get('date','').startswith(f'{year}-{month}') and
                (d['field'] not in ('paranaStart','paranaEnd') or d['status']!='WITHIN_EXISTING_BAND' or d['basisStatus']!='MATCH')]
            context.append(dict(year=year,month=month,source=other['source'],exactPointMatches=other['canonicalPlace']==row['canonicalPlace'],exceptions=relevant))
        report.append(dict(city=city,point=row['canonicalPlace'],fields=groups,source=row['source'],
            discreteExactAgreement={f['field']: f['compared'] for f in row['fields'][:3] if not f['disagreements']},
            paranaBounds=dict(total=len(bounds),samePrintedMinuteAndBasis=exact,withinDeclaredBandAndBasis=len(usable),
                withinBandDifferentPrintedMinute=len(usable)-exact,zeroSecondDelta=sum(d['deltaSeconds']==0 for d in usable),
                exceptionRows=[d for d in bounds if d not in usable]),
            unsupportedAssumptions=['Elevation 0 m is not supplied by the source.', 'Exact export binary/settings and timezone database version are unpublished.',
                'Minute agreement is not proof of identical astronomical instants.', 'Related upstream code is supporting evidence, not an authenticated Build 5 binary.'],
            context=context,carryoverChecks=row['contextChecks'],
            recommendation='Submit exact 2026 OBSERVANCES scope for qualified review; keep withheld until review and owner decision.' if city in PRIORITY else 'Retain whole-year hold; see dated exceptions and source findings.',
            noPublicationApproval=True))
    write(HERE/'ai-assisted-review.json', dict(classification='AI_ASSISTED_EVIDENCE_REVIEW',locations=report))
    # Evidence policy is a new unsigned PROPOSAL, never installed into the runtime gate.
    policy = dict(id='vaisnavacalendar-info-gcal-text',revision='2026-09-21-ai-assisted-proposed',
        description='Unsigned 2026 OBSERVANCES-only evidence proposal; original bands and exact points preserved. AI-assisted research is not qualified review or publication approval.',
        evidence=[evidence(OLD/'REFERENCE-POLICY.md','PROPOSED_POLICY_NOT_APPROVED'),evidence(HERE/'ai-assisted-review.json','AI_ASSISTED_EVIDENCE_REVIEW'),
                  evidence(HERE/'coverage-inventory.json','REPRODUCED_COMPARISONS_NOT_APPROVAL'),
                  evidence(HERE/'SOURCE-FINDINGS.md','AI_ASSISTED_SOURCE_INVESTIGATION_NOT_APPROVAL'),
                  evidence(HERE/'source-checks.json','HASHED_RESEARCH_SOURCES_NOT_APPROVAL')])
    write(HERE/'reference-policy.proposed.json', policy)
    for tier in ('priority','hold'):
        members=[]; sources=[]
        for row in report:
            city=row['city']
            if (city in PRIORITY) != (tier=='priority'): continue
            m=read(HERE/f'measurements/{city}-2026.json')['member']
            members.append(dict(place=m['place'],tradition='iskcon',year=2026,coverage=m['coverage'],fields=['OBSERVANCES']))
            sources.append(evidence(HERE/f'measurements/{city}-2026.json','AI_ASSISTED_MEASUREMENT_NOT_APPROVAL'))
            for year in (2025,2026,2027):
                meta=read(HERE/f'comparison-inputs/calendar-{city}-{year}.json')
                sources.append(evidence(ROOT/meta['file'],'DESIGNATED_REFERENCE_CONTEXT_NOT_APPROVAL'))
        write(HERE/f'proposals/{tier}.request.json',dict(members=members,referencePolicy=policy,evidence=sources))
    # Explicit optional alternative, not an addition to the seven first-release candidates.
    hold_request=read(HERE/'proposals/hold.request.json')
    sydney=next(r for r in report if r['city']=='sydney')
    narrow_member=next(m for m in hold_request['members'] if m['place']==sydney['point']).copy()
    narrow_member['coverage']={'from':'2026-01-01','through':'2026-12-04'}
    write(HERE/'proposals/alternative-sydney-through-december-04.request.json',
          dict(members=[narrow_member],referencePolicy=policy,evidence=hold_request['evidence']))
    lines=['# AI-assisted evidence review', '', '**AI_ASSISTED_EVIDENCE_REVIEW. Unsigned; not qualified-human review or owner approval.**', '',
        'Scope: exact reference points, 2026 OBSERVANCES only. All 45 location/year results and comparisons reproduce the prior snapshot. All 15 freshly retrieved 2026 files have identical hashes. 2025/2027 remain boundary research, not release scope.', '',
        '| Point | Fast dates / names / types | Parana bounds: same minute + basis / within band + basis / total | Status |', '|---|---|---|---|']
    for r in report:
        a=r['paranaBounds']; exact=r['discreteExactAgreement']
        lines.append(f"| {r['city']} | {', '.join(f'{k}: {v}' for k,v in exact.items()) or 'See conflicting dates'} | {a['samePrintedMinuteAndBasis']} / {a['withinDeclaredBandAndBasis']} / {a['total']} | {'Awaiting qualified review and owner decision' if r['city'] in PRIORITY else 'HOLD'} |")
    lines += ['', 'The middle count includes the first count. These are counts, not an overall accuracy score. Minute agreement is not exact-instant agreement. Solar bands remain -15..75 seconds; lunar bands remain -180..75 seconds. Basis conflicts and stale-DST clocks never count as passing timing evidence.', '',
        'The machine-readable [review](ai-assisted-review.json) lists every point, field group, applicable dispute/question, source URL/hash/time, unsupported assumption, exception date and complete December/January context exceptions. [Comparisons](coverage-inventory.json) preserve all 45 years/points, raw timing deltas and daily-label disagreements.', '',
        'EVENTS remain outside the proposal: partial catalog mapping and unavailable precise festival fast-end anchors. DAILY_ASTRONOMY remains outside the public schema, with documented tithi/nakshatra disagreements and no complete standalone sunrise/sunset oracle. Nearby GPS points, different elevation, other years and other traditions receive no inferred approval.', '',
        'See [SOURCE-FINDINGS.md](SOURCE-FINDINGS.md) for the rule investigation, [DECISIONS.md](DECISIONS.md) for remaining decisions, and [HANDOFF.md](HANDOFF.md) for engineering and verification. Runtime disputes and prior evidence are unchanged.']
    (HERE/'AI-ASSISTED-REVIEW.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print('Reproduced 45 comparisons; prepared 7 candidates and 8 holds, all unsigned.')

if __name__=='__main__': main()
