package org.panchang.verify.vaisnava

import org.panchang.verify.harvest.ParseReport
import org.panchang.verify.harvest.ParsedArtifact
import org.panchang.verify.harvest.ResponseShapeException
import org.panchang.verify.harvest.Unparsed
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.Locale

/** A fully parsed community text calendar. */
data class VaisnavaCalendar(
    val header: VaisnavaCalendarHeader,
    val days: List<VaisnavaDay>,
    val sankrantis: List<SankrantiNote>,
)

/**
 * Parser for the fixed-width text calendars published by vaisnavacalendar.info
 * (generator: "Gaurabda Calendar 11").
 *
 * This is the strongest factor-3 anchor available: it is machine-readable, published
 * per-city for 220-odd locations including every city in our reference grid, states its
 * own coordinates and UTC offset, distinguishes local standard time from daylight saving
 * time per line, and names the rule bounding each end of a parana window. HTML calendar
 * pages give none of that.
 *
 * The format is column-aligned, and the columns overflow. A real 2026 line reads
 * `25 Jun 2026 Th   Ekadasi (not suitable for fasting)G Swati` — the tithi text runs
 * flush into the paksa column with no separating space. A whitespace-splitting parser
 * drops that line, and dropping Ekadasi lines specifically is the worst possible failure
 * for this module. The parser therefore reads the column offsets from the emitted header
 * rule and only falls back to a regex when the fixed layout does not hold, reporting the
 * line if neither works.
 */
object VaisnavaCalendarTxtParser {

    private const val SOURCE = "vaisnavacalendar-txt"

    private val DATE_LINE = Regex("""^([ \d]\d) ([A-Z][a-z]{2}) (\d{4}) ([A-Z][a-z])(.*)$""")
    private val MASA_HEADER = Regex("""^\s*(.+?)\s+Masa,\s+Gaurabda\s+(\d+)\s*(.*)$""")
    private val CITY_HEADER =
        Regex("""^\s*(.+?)\s+\(([0-9]{1,3}[NS][0-9]{1,2}\s+[0-9]{1,3}[EW][0-9]{1,2}),\s*([+-]?\d{1,2}:\d{2})\)\s*$""")
    private val COLUMN_HEADER = Regex("""^\s*DATE\s+TITHI\s+PAKSA\s+NAKSATRA\s+FAST\s*$""")
    private val PLAIN_RULE = Regex("""^-{5,}$""")
    private val SANKRANTI_RULE = Regex("""^-+\s*(\S.*?\S)\s*-+$""")
    private val PARANA = Regex(
        """^Break fast (\d{1,2}:\d{2}) \(([^)]*)\)\s*-\s*(\d{1,2}:\d{2}) \(([^)]*)\)\s*(LT|DST)\s*$""",
    )

    /**
     * The open-ended form: "Break fast after 10:50 (1/4 of tithi) LT".
     *
     * Rare — three days across the ten grid cities in 2026 — and printed only when the
     * source states a lower bound alone. Kept as a distinct shape with a null end rather
     * than folded into [PARANA] with a fabricated upper bound.
     */
    private val PARANA_OPEN_ENDED = Regex(
        """^Break fast after (\d{1,2}:\d{2}) \(([^)]*)\)\s*(LT|DST)\s*$""",
    )
    private val FASTING_FOR = Regex("""^Fasting for (\S.*?)\s*$""")
    private val NOTES_MARKER = Regex("""^\s*Notes:\s*$""")
    private val GENERATOR = Regex("""^\s*Generated by (\S.*?)\s*$""")

    private val DATE_FORMAT: DateTimeFormatter = DateTimeFormatter.ofPattern("d MMM yyyy", Locale.US)

    /** Fallback for lines where the tithi text has overrun the paksa column. */
    private val LOOSE_BODY = Regex("""^\s*(\S.*?)\s*([GK])\s+(\S+)\s*(\*)?\s*$""")

    fun parse(text: String): ParsedArtifact<VaisnavaDay> {
        val calendar = parseCalendar(text)
        return ParsedArtifact(calendar.first.days, calendar.second)
    }

    fun parseCalendar(text: String): Pair<VaisnavaCalendar, ParseReport> {
        val lines = text.replace("\r\n", "\n").split("\n")

        val days = mutableListOf<VaisnavaDay>()
        val sankrantis = mutableListOf<SankrantiNote>()
        val unparsed = mutableListOf<Unparsed>()
        val warnings = mutableListOf<String>()

        var city: String? = null
        var coordinates: String? = null
        var utcOffset: String? = null
        var generator: String? = null
        var masa: String? = null
        var gaurabda: Int? = null

        // Column offsets, re-read from every column-header line the file contains. The
        // file repeats the header once per masa; if the generator ever changes its widths
        // mid-file we follow it rather than assuming.
        var paksaCol = -1
        var naksatraCol = -1

        var current: MutableDay? = null
        var inNotes = false

        fun flush() {
            current?.let { days += it.build() }
            current = null
        }

        for ((index, rawLine) in lines.withIndex()) {
            val lineNo = index + 1
            val line = rawLine.trimEnd()
            if (line.isBlank()) continue

            if (inNotes) continue

            if (NOTES_MARKER.matches(line)) {
                flush()
                inNotes = true
                continue
            }

            if (COLUMN_HEADER.matches(line)) {
                // Right-aligned single letter under the last character of "PAKSA".
                paksaCol = line.indexOf("PAKSA") + "PAKSA".length - 1
                naksatraCol = line.indexOf("NAKSATRA")
                continue
            }

            if (PLAIN_RULE.matches(line)) continue

            val sankranti = SANKRANTI_RULE.matchEntire(line)
            if (sankranti != null) {
                val body = sankranti.groupValues[1]
                sankrantis += SankrantiNote(
                    name = body.substringBefore(" (").trim(),
                    text = body.trim(),
                )
                continue
            }

            val masaMatch = MASA_HEADER.matchEntire(line)
            if (masaMatch != null) {
                flush()
                masa = masaMatch.groupValues[1].trim()
                gaurabda = masaMatch.groupValues[2].toIntOrNull()
                if (generator == null) generator = masaMatch.groupValues[3].trim().ifEmpty { null }
                continue
            }

            val cityMatch = CITY_HEADER.matchEntire(line)
            if (cityMatch != null) {
                val name = cityMatch.groupValues[1].trim()
                if (city != null && city != name) {
                    warnings += "line $lineNo: city header changed from '$city' to '$name' " +
                        "inside a single file."
                }
                city = name
                coordinates = cityMatch.groupValues[2].trim()
                utcOffset = cityMatch.groupValues[3].trim()
                continue
            }

            val generatorMatch = GENERATOR.matchEntire(line)
            if (generatorMatch != null) {
                generator = generatorMatch.groupValues[1].trim()
                continue
            }

            val dateMatch = DATE_LINE.matchEntire(line)
            if (dateMatch != null) {
                flush()
                val day = dateMatch.groupValues[1].trim()
                val mon = dateMatch.groupValues[2]
                val year = dateMatch.groupValues[3]
                val weekday = dateMatch.groupValues[4]
                val date = try {
                    LocalDate.parse("$day $mon $year", DATE_FORMAT)
                } catch (e: Exception) {
                    unparsed += Unparsed("line $lineNo", line, "unparsable date: ${e.message}")
                    continue
                }
                // Cheap independent check that the columns are aligned as we believe: the
                // printed weekday must agree with the printed date. A mismatch means the
                // layout assumption is wrong somewhere upstream of here.
                val expectedWeekday = date.dayOfWeek
                    .getDisplayName(java.time.format.TextStyle.SHORT, Locale.US)
                    .take(2)
                if (!expectedWeekday.equals(weekday, ignoreCase = true)) {
                    warnings += "line $lineNo: printed weekday '$weekday' does not match $date " +
                        "(expected '$expectedWeekday')."
                }

                val body = splitBody(line, paksaCol, naksatraCol)
                if (body == null) {
                    unparsed += Unparsed(
                        "line $lineNo",
                        line,
                        "date line recognised but tithi/paksa/naksatra columns could not be split",
                    )
                    continue
                }
                current = MutableDay(
                    date = date.toString(),
                    weekdayAbbrev = weekday,
                    tithi = body.tithi,
                    paksa = body.paksa,
                    naksatra = body.naksatra,
                    fastMarked = body.fastMarked,
                    masa = masa,
                    gaurabda = gaurabda,
                )
                continue
            }

            // Anything else that is indented belongs to the day above it.
            if (rawLine.startsWith("        ")) {
                val content = line.trim()
                val day = current
                if (day == null) {
                    unparsed += Unparsed("line $lineNo", content, "continuation line with no preceding date")
                    continue
                }
                val paranaMatch = PARANA.matchEntire(content)
                if (paranaMatch != null) {
                    day.parana = ParanaWindow(
                        start = paranaMatch.groupValues[1],
                        startBasis = paranaMatch.groupValues[2].trim(),
                        end = paranaMatch.groupValues[3],
                        endBasis = paranaMatch.groupValues[4].trim(),
                        clock = paranaMatch.groupValues[5],
                    )
                    continue
                }
                val openEnded = PARANA_OPEN_ENDED.matchEntire(content)
                if (openEnded != null) {
                    day.parana = ParanaWindow(
                        start = openEnded.groupValues[1],
                        startBasis = openEnded.groupValues[2].trim(),
                        end = null,
                        endBasis = null,
                        clock = openEnded.groupValues[3],
                    )
                    continue
                }
                if (content.startsWith("Break fast")) {
                    // Recognised as a parana line but not in the expected shape. Never
                    // silently discard one of these: the parana window is the single most
                    // consequential field this source provides.
                    unparsed += Unparsed("line $lineNo", content, "unrecognised 'Break fast' window format")
                    continue
                }
                val fastingMatch = FASTING_FOR.matchEntire(content)
                if (fastingMatch != null) {
                    day.fastingFor = fastingMatch.groupValues[1]
                    continue
                }
                day.events += content
                continue
            }

            unparsed += Unparsed("line $lineNo", line, "unrecognised line")
        }
        flush()

        if (city == null) {
            throw ResponseShapeException(
                SOURCE,
                "no city header line of the form 'City [Country] (23N25 88E23, +5:30)'. " +
                    "This does not look like a Gaurabda Calendar text export.",
            )
        }
        if (days.isEmpty()) {
            throw ResponseShapeException(SOURCE, "no day rows recovered from ${lines.size} lines.")
        }

        val calendar = VaisnavaCalendar(
            header = VaisnavaCalendarHeader(
                city = city,
                coordinates = coordinates.orEmpty(),
                utcOffset = utcOffset.orEmpty(),
                generator = generator,
            ),
            days = days,
            sankrantis = sankrantis,
        )
        return calendar to ParseReport(days.size, unparsed, warnings)
    }

    private data class Body(
        val tithi: String,
        val paksa: String,
        val naksatra: String,
        val fastMarked: Boolean,
    )

    private fun splitBody(line: String, paksaCol: Int, naksatraCol: Int): Body? {
        // Preferred path: fixed columns taken from the emitted header.
        if (paksaCol in 0 until line.length && naksatraCol > paksaCol) {
            val paksa = line[paksaCol]
            if (paksa == 'G' || paksa == 'K') {
                val tithi = line.substring(DATE_FIELD_WIDTH.coerceAtMost(paksaCol), paksaCol).trim()
                val tail = if (line.length > naksatraCol) line.substring(naksatraCol).trim() else ""
                val tokens = tail.split(Regex("\\s+")).filter { it.isNotEmpty() }
                val naksatra = tokens.firstOrNull() ?: return null
                val fast = tokens.drop(1).any { it == "*" }
                if (tithi.isNotEmpty()) return Body(tithi, paksa.toString(), naksatra, fast)
            }
        }
        // Fallback: the columns did not hold. Do not give up on the line yet.
        val rest = if (line.length > DATE_FIELD_WIDTH) line.substring(DATE_FIELD_WIDTH) else return null
        val m = LOOSE_BODY.matchEntire(rest) ?: return null
        return Body(
            tithi = m.groupValues[1].trim(),
            paksa = m.groupValues[2],
            naksatra = m.groupValues[3],
            fastMarked = m.groupValues[4] == "*",
        )
    }

    /** Width of the `DD Mon YYYY Dy` date field, including its trailing gutter. */
    private const val DATE_FIELD_WIDTH = 15

    private class MutableDay(
        val date: String,
        val weekdayAbbrev: String,
        val tithi: String,
        val paksa: String,
        val naksatra: String,
        val fastMarked: Boolean,
        val masa: String?,
        val gaurabda: Int?,
    ) {
        val events = mutableListOf<String>()
        var fastingFor: String? = null
        var parana: ParanaWindow? = null

        fun build() = VaisnavaDay(
            date = date,
            weekdayAbbrev = weekdayAbbrev,
            tithi = tithi,
            paksa = paksa,
            naksatra = naksatra,
            fastMarked = fastMarked,
            masa = masa,
            gaurabda = gaurabda,
            events = events.toList(),
            fastingFor = fastingFor,
            parana = parana,
        )
    }
}
